/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pedidos;

import javax.swing.JOptionPane;

/**
 *
 * @author Jose Mafla
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Conexion conectar = Conexion.getInstance();
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipoCarneEntry = new javax.swing.JTextField();
        cantidadCarnesEntry = new javax.swing.JTextField();
        tipoPanEntry = new javax.swing.JTextField();
        bebidaEntry = new javax.swing.JTextField();
        CrearPedidoBoton = new javax.swing.JButton();
        crearOtroPedidoBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Creemos un pedido");

        jLabel2.setText("Insertar tipo de carne:  ");

        jLabel3.setText("Insertar cantidad de carnes:  ");

        jLabel4.setText("Insertar tipo de pan:  ");

        jLabel5.setText("Insertar bebida: ");

        tipoCarneEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCarneEntryActionPerformed(evt);
            }
        });

        cantidadCarnesEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadCarnesEntryActionPerformed(evt);
            }
        });

        CrearPedidoBoton.setText("Crear pedido");
        CrearPedidoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPedidoBotonActionPerformed(evt);
            }
        });

        crearOtroPedidoBoton.setText("Crear otro pedido parecido");
        crearOtroPedidoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearOtroPedidoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCarneEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cantidadCarnesEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addComponent(tipoPanEntry)
                                .addComponent(bebidaEntry))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CrearPedidoBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(crearOtroPedidoBoton)))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoCarneEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadCarnesEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoPanEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bebidaEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearPedidoBoton)
                    .addComponent(crearOtroPedidoBoton))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoCarneEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCarneEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCarneEntryActionPerformed

    private void cantidadCarnesEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadCarnesEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadCarnesEntryActionPerformed

    private void CrearPedidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPedidoBotonActionPerformed
        AccionesEmpleado pedidoAcciones = new  AccionesEmpleado();
        Pedido pedido = new Pedido();
        
        String valorTipoCarne = tipoCarneEntry.getText();
        int valorCantidadCarnes = Integer.parseInt(cantidadCarnesEntry.getText());
        String valorTipoPan = tipoPanEntry.getText();
        String valorBebida = bebidaEntry.getText();
        
        pedido.setTipoCarne(valorTipoCarne);
        pedido.setCantidadCarnes(valorCantidadCarnes);
        pedido.setTipoPan(valorTipoPan);
        pedido.setBebida(valorBebida);
        
        pedidoAcciones.crear(pedido);
    }//GEN-LAST:event_CrearPedidoBotonActionPerformed

    private void crearOtroPedidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearOtroPedidoBotonActionPerformed
        AccionesEmpleado pedidoAcciones = new  AccionesEmpleado();
        Pedido pedidoOriginal = new Pedido();
        
        String valorTipoCarne = tipoCarneEntry.getText();
        int valorCantidadCarnes = Integer.parseInt(cantidadCarnesEntry.getText());
        String valorTipoPan = tipoPanEntry.getText();
        String valorBebida = bebidaEntry.getText();
        
        pedidoOriginal.setTipoCarne(valorTipoCarne);
        pedidoOriginal.setCantidadCarnes(valorCantidadCarnes);
        pedidoOriginal.setTipoPan(valorTipoPan);
        pedidoOriginal.setBebida(valorBebida);
        
        Forma pedidoOtro = pedidoOriginal.clone();
        
        pedidoAcciones.crearOtro((Pedido) pedidoOtro);
    }//GEN-LAST:event_crearOtroPedidoBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearPedidoBoton;
    private javax.swing.JTextField bebidaEntry;
    private javax.swing.JTextField cantidadCarnesEntry;
    private javax.swing.JButton crearOtroPedidoBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tipoCarneEntry;
    private javax.swing.JTextField tipoPanEntry;
    // End of variables declaration//GEN-END:variables
}
